export const SERVICEABLE_CITIES = [

    // BAY AREA
    "san mateo",
    "foster city",
    "burlingame",
    "san carlos",
    "redwood city",
    "belmont",
    "menlo park",
    "palo alto",
    "mountain view",
    "los altos",
    "sunnyvale",
    "cupertino",
    "santa clara",
    "san jose",
    "saratoga",
    "campbell",
    "los gatos",
    "milpitas",
    "livermore",
    "dublin",
    "ruby hill",
    "san ramon",
    "danville",
    "pleasanton",

    // SEATTLE
    "seattle",
    "bellevue",
    "redmond",
    "kirkland",
    "bothell",
    "lynnwood",
    "everett",
    "mill creek",
    "woodinville",
    "sammamish",
    "issaquah",
    "newcastle",
    "renton",
    "kent",
    "kenmore",
    "lake forest park",
    "maple valley",
    "snohomish",
    "auburn"

]; 